# Makefile

all:
	gcc teste_all.c Unity/unity.c -o teste_all.x
	./teste_all.x
	rm teste_all.x


queue:
	gcc teste_queue.c Unity/unity.c -o teste_queue.x
	./teste_queue.x
	rm teste_queue.x

tree:
	gcc teste_tree.c Unity/unity.c -o teste_tree.x
	./teste_tree.x
	rm teste_tree.x

utils:
	gcc teste_utils.c Unity/unity.c -o teste_utils.x
	./teste_utils.x
	rm teste_utils.x

