# Makefile

all:
	@echo "Bem vindo aos testes do huffman. Por favor, escolha uma opção."
	@echo "Digite make (estrutua de dados que deseja testar)."

	@echo "Opcoes:"
	@echo "queue"
	@echo "arvore"


queue:
	gcc teste_queue.c Unity/unity.c -o teste_queue.x
	./teste_queue.x
	rm teste_queue.x

arvore:
	gcc teste_arvore.c Unity/unity.c -o teste_arvore.x
	./teste_arvore.x
	rm teste_arvore.x
